# Site settings 
title: Aprendizado de Máquina e Aprendizagem Profunda
email: zenilton@pucminas.br
description: "Course materials and notes for PUC Minas class 'Tópicos em Computação 2: Aprendizado de Máquina e Aprendizagem Profunda'."
baseurl: "http://zenilton-patrocinio.github.io/deep-learning-2020"
url: "http://zenilton-patrocinio.github.io/deep-learning-2020"
#twitter_username: cs231n
github_username:  zenilton-patrocinio

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
